name: Test public reusable workflow
on: 
  workflow_call:
    secrets:
      ECR_REGISTRY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    steps:

    - shell: bash
      run: |
        echo ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"|base64
        echo aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"|base64
        echo aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"|base64
        echo ECR_REGISTRY: "${{ secrets.ECR_REGISTRY }}"|base64
